<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jil</string>
	</array>
	<key>name</key>
	<string>Autosys</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment block</string>
			<key>match</key>
			<string>/\*.*\*/\s*$\n?</string>
			<key>name</key>
			<string>comment.block.autosys</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Box or Job identification</string>
			<key>match</key>
			<string>(?:box_name):</string>
			<key>name</key>
			<string>keyword.control.autosys</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.autosys</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.autosys</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.autosys</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.autosys</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Box flow controls</string>
			<key>match</key>
			<string>^\s*((?:delete_box|insert_job|update_job):)\s*([A-Za-z0-9_]*)*(\$S)([A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>meta.box.control.autosys</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.autosys</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.jobname.autosys</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>What does this box run?</string>
			<key>match</key>
			<string>^\s*(command:)\s*(autojob\.sh)\s+([A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>meta.command.autosys</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.autosys</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.autosys</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>What kind of box is this?</string>
			<key>match</key>
			<string>(job_type:)\s*([bc])</string>
			<key>name</key>
			<string>meta.box.type.autosys</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.autosys</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.autosys</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(permission:)\s*((?:[gmw][xe],?\s*)+)</string>
			<key>name</key>
			<string>meta.attribute.permission.autosys</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Generic Keywords that don't have specified parameters</string>
			<key>match</key>
			<string>(?:date_conditions|run_calendar|start_times|condition|alarm_if_fail|machine|description):</string>
			<key>name</key>
			<string>keyword.control.autosys</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.autosys</string>
	<key>uuid</key>
	<string>4cd28efc-83c1-4a3e-b9ab-5bbda5eaa863</string>
</dict>
</plist>
